// Automatically generated by MockGen. DO NOT EDIT!
// Source: tfl-service.go

package mocks

import (
	gomock "github.com/golang/mock/gomock"
	go_tfl "github.com/thoeni/go-tfl"
)

// Mock of TflService interface
type MockTflService struct {
	ctrl     *gomock.Controller
	recorder *_MockTflServiceRecorder
}

// Recorder for MockTflService (not exported)
type _MockTflServiceRecorder struct {
	mock *MockTflService
}

func NewMockTflService(ctrl *gomock.Controller) *MockTflService {
	mock := &MockTflService{ctrl: ctrl}
	mock.recorder = &_MockTflServiceRecorder{mock}
	return mock
}

func (_m *MockTflService) EXPECT() *_MockTflServiceRecorder {
	return _m.recorder
}

func (_m *MockTflService) GetStatusFor(lines []string) (map[string]go_tfl.Report, error) {
	ret := _m.ctrl.Call(_m, "GetStatusFor", lines)
	ret0, _ := ret[0].(map[string]go_tfl.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockTflServiceRecorder) GetStatusFor(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetStatusFor", arg0)
}
